<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="Home.aspx.cs" Inherits="DataBaseConnectivity.Home" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
        <center>
            Employee Information
        </center>
    </div>
        <div>
            <span>Employee Name:</span>
        </div>
        <div>
            <asp:TextBox ID="txtname" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ID="reqname" runat="server"
                 ControlToValidate="txtname"
                 ErrorMessage="Please Enter Name."
                 Text="*"
                 ForeColor="Red"></asp:RequiredFieldValidator>
            <asp:RegularExpressionValidator ID="regname" runat="server"
                 ControlToValidate="txtname"
                 ValidationExpression="^[A-Za-z ]+$"
                 ErrorMessage="Invalid Name."
                 Text="*"
                 ForeColor="Red"></asp:RegularExpressionValidator>
        </div>
        <div>
            <span>Employee City:</span>
        </div>
        <div>
            <asp:DropDownList ID="ddlcity" runat="server">
                <asp:ListItem Value="" Text="---- Select City---" disabled></asp:ListItem>
                <asp:ListItem Value="Rajkot" Text="Rajkot"></asp:ListItem>
                <asp:ListItem Value="Junagadh" Text="Junagadh"></asp:ListItem>
                <asp:ListItem Value="Ahmedabad" Text="Ahmedabad"></asp:ListItem>
                <asp:ListItem Value="Jamnagar" Text="Jamnagar"></asp:ListItem>
            </asp:DropDownList>
        </div>
        <div>
            <span>Emplooyee Gender:</span>
        </div>
        <div>
            <asp:RadioButton ID="rbtmale" runat="server"
                 Text="Male" Checked="true" GroupName="gender" />
            &nbsp;&nbsp;
            <asp:RadioButton ID="rbtfemale" runat="server"
                 Text="Female" GroupName="gender" />
        </div>
        <div>
            <span>Employee Mobile:</span>
        </div>
        <div>
            <asp:TextBox ID="txtmobile" runat="server"></asp:TextBox>
            <asp:RequiredFieldValidator ID="reqmobile" runat="server"
                 ControlToValidate="txtmobile"
                 ErrorMessage="Please Enter Mobile Number."
                 Text="*"
                 ForeColor="Red"></asp:RequiredFieldValidator>
            <asp:RegularExpressionValidator ID="regmobile"
                 runat="server"
                 ControlToValidate="txtmobile"
                 ValidationExpression="^[0-9]{10}$"
                 ErrorMessage="Invalid Mobile Number."
                 Text="*"
                 ForeColor="Red"></asp:RegularExpressionValidator>
        </div>
        <div>
            <asp:ValidationSummary ID="valsum" runat="server"
                 ShowSummary="true"
                 HeaderText="Resolve Following Errors."
                 DisplayMode="BulletList"
                 ForeColor="Red" />
        </div>
        <div>
            <asp:GridView ID="gvempdetail" runat="server"
                 AutoGenerateColumns="false"
                 DataKeyNames="ID"
                 AutoGenerateEditButton="true"
                 AutoGenerateDeleteButton="true" AllowPaging="True" BackColor="White" BorderColor="#999999" BorderStyle="Solid" BorderWidth="1px" CellPadding="3" ForeColor="Black" GridLines="Vertical" OnPageIndexChanging="gvempdetail_PageIndexChanging" PageSize="5" OnRowEditing="gvempdetail_RowEditing" OnRowCancelingEdit="gvempdetail_RowCancelingEdit" OnRowDeleting="gvempdetail_RowDeleting" OnRowUpdating="gvempdetail_RowUpdating">
                <AlternatingRowStyle BackColor="#CCCCCC" />
                <FooterStyle BackColor="#CCCCCC" />
                <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#999999" ForeColor="Black" HorizontalAlign="Center" />
                <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                <SortedAscendingCellStyle BackColor="#F1F1F1" />
                <SortedAscendingHeaderStyle BackColor="#808080" />
                <SortedDescendingCellStyle BackColor="#CAC9C9" />
                <SortedDescendingHeaderStyle BackColor="#383838" />
                <Columns>
                    <asp:BoundField DataField="ID" HeaderText="ID" ReadOnly />
                    <asp:BoundField DataField="Name" HeaderText="NAME" />
                    <asp:BoundField DataField="City" HeaderText="CITY" />
                    <asp:BoundField DataField="Gender" HeaderText="GENDER" />
                    <asp:BoundField DataField="Mobile" HeaderText="MOBILE" />
                </Columns>
            </asp:GridView>
        </div>
        <div>
            <span>Record Display Using Repeater Control</span>
        </div>
        <div>
            <table border="1">
            <asp:Repeater ID="rptemployee" runat="server">
                <HeaderTemplate>
                    <tr>
                        <th>ID</th>
                        <th>NAME</th>
                        <th>CITY</th>
                        <th>GENDER</th>
                        <th>MOBILE</th>
                    </tr>
                </HeaderTemplate>
                <ItemTemplate>
                    <tr>
                        <td><%# Eval("ID") %></td>
                        <td><%# Eval("Name") %></td>
                        <td><%# Eval("City") %></td>
                        <td><%# Eval("Gender") %></td>
                        <td><%# Eval("Mobile") %></td>
                    </tr>
                </ItemTemplate>
                <FooterTemplate>
                    </table>
                </FooterTemplate>
            </asp:Repeater>
        </div>
        <div>
            <asp:Button ID="btnsumbit" runat="server"
                 Text="Submit" OnClick="btnsumbit_Click" />
        </div>

    </form>
</body>
</html>
